# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ('posted',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 2, 5, 5, 39, 407357, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
