# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161102_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
