# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-05 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogarticle_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='photo',
        ),
    ]
